CREATE SEQUENCE SEQ_ADMIN;
CREATE TABLE TBL_ADMIN(
   ID NUMBER CONSTRAINT PK_ADMIN PRIMARY KEY,
   ADMIN_ACCOUNT VARCHAR2(1000) CONSTRAINT UK_ACCOUNT UNIQUE NOT NULL,
   ADMIN_PASSWORD VARCHAR2(1000) DEFAULT '1234',
   ADMIN_NAME VARCHAR2(1000) NOT NULL,
   ADMIN_PHONE VARCHAR2(1000) NOT NULL,
   ADMIN_EMAIL VARCHAR2(1000) NOT NULL
);

SELECT * FROM TBL_ADMIN;