CREATE SEQUENCE SEQ_MEMBER;

CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_EMAIL VARCHAR2(1000) NOT NULL,
	MEMBER_PASSWORD VARCHAR2(1000) NOT NULL,
	MEMBER_NAME VARCHAR2(1000) NOT NULL,
	MEMBER_AGE NUMBER DEFAULT 0,
	MEMBER_GENDER VARCHAR2(1000) DEFAULT '선택안함',
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE
);
SELECT * FROM TBL_MEMBER;

CREATE SEQUENCE SEQ_FEED;

DROP TABLE TBL_FEED;
DROP SEQUENCE SEQ_FEED;

CREATE TABLE TBL_FEED(
	ID NUMBER CONSTRAINT PK_FEED PRIMARY KEY,
	CREATE_DATE DATE DEFAULT SYSDATE,
	UPDATE_DATE DATE DEFAULT SYSDATE,
	FEED_CONTENT VARCHAR2(2000) NOT NULL,
	MEMBER_ID NUMBER NOT NULL,
	CONSTRAINT FK_FEED_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID)	
);

SELECT * FROM TBL_FEED



