CREATE SEQUENCE SEQ_POST;

CREATE TABLE TBL_POST (
	ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
	POST_TITLE VARCHAR2(1000) NOT NULL,
	POST_CONTENT VARCHAR2(1000) NOT NULL,
	POST_READ_COUNT NUMBER DEFAULT 0,
	MEMBER_ID NUMBER NOT NULL,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_POST_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID) ON DELETE CASCADE
);

SELECT * FROM TBL_POST;
SELECT COUNT(*) FROM TBL_POST;


INSERT INTO TBL_POST
(ID, POST_TITLE, POST_CONTENT, MEMBER_ID)
(SELECT SEQ_POST.NEXTVAL, POST_TITLE, POST_CONTENT, MEMBER_ID FROM TBL_POST);

DELETE FROM TBL_POST
WHERE MOD(ID,29) = 0 ;
