CREATE SEQUENCE SEQ_ADMIN;
CREATE TABLE TBL_ADMIN(
      ID NUMBER CONSTRAINT PK_ADMIN PRIMARY KEY,
      ADMIN_ACCOUNT VARCHAR2(1000) CONSTRAINT UK_ACCOUNT UNIQUE NOT NULL,
      ADMIN_PASSWORD VARCHAR2(1000) DEFAULT '1234',
      ADMIN_NAME VARCHAR2(1000) NOT NULL,
      ADMIN_PHONE VARCHAR2(1000) NOT NULL,
      ADMIN_EMAIL VARCHAR2(1000) NOT NULL,
      CREATED_DATE DATE DEFAULT SYSDATE,
      UPDATED_DATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SEQ_COURSE;
CREATE TABLE TBL_COURSE(
       ID NUMBER CONSTRAINT PK_COURSE PRIMARY KEY,
       COURSE_TYPE VARCHAR2(20),
       COURSE_IS_VOLUNTEER CHAR(1) DEFAULT 'N',
       COURSE_NAME VARCHAR2(1000) NOT NULL,
       COURSE_DISTANCE VARCHAR2(1000) NOT NULL,
       COURSE_SCHEDULE VARCHAR2(1000) NOT NULL,
       COURSE_THEME VARCHAR2(1000) NOT NULL,
       COURSE_CONTENT VARCHAR2(1000) NOT NULL,
       COURSE_FILE_PATH VARCHAR2(1000),
       COURSE_FILE_SIZE VARCHAR2(1000),
       COURSE_FILE_NAME VARCHAR2(1000),
       ADMIN_ID NUMBER NOT NULL,
       CREATED_DATE DATE DEFAULT SYSDATE,
       UPDATED_DATE DATE DEFAULT SYSDATE,
       CONSTRAINT FK_COURSE_ADMIN FOREIGN KEY(ADMIN_ID)
       REFERENCES TBL_ADMIN(ID)  ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
       ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
       MEMBER_EMAIL VARCHAR2(1000) UNIQUE NOT NULL,
       MEMBER_PASSWORD VARCHAR2(1000),
       MEMBER_NICKNAME VARCHAR2(1000) UNIQUE,
       MEMBER_TELL VARCHAR2(1000),
       MEMBER_BIRTH DATE DEFAULT SYSDATE,
       MEMBER_GENDER VARCHAR2(1000) DEFAULT '선택안함',
       MEMBER_POINT NUMBER DEFAULT 0,
       MEMBER_IS_ACT CHAR(1) DEFAULT 'Y' NOT NULL,
       MEMBER_FILE_PATH VARCHAR2(1000),
       MEMBER_FILE_NAME VARCHAR2(1000),
       MEMBER_FILE_SIZE VARCHAR2(1000) DEFAULT '',
       CREATED_DATE DATE DEFAULT SYSDATE,
       UPDATED_DATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SEQ_FILE;
CREATE TABLE TBL_FILE (
    ID NUMBER CONSTRAINT PK_FILE PRIMARY KEY,
    FILE_PATH VARCHAR2(1000) NOT NULL,
    FILE_NAME VARCHAR2(1000) NOT NULL,
    FILE_SIZE VARCHAR2(200) DEFAULT '',
    CREATED_DATE DATE DEFAULT SYSDATE,
    UPDATED_DATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SEQ_MESSAGE;
CREATE TABLE TBL_MESSAGE(
    ID NUMBER CONSTRAINT PK_MESSAGE_ALL PRIMARY KEY,
    MESSAGE_ALL_CONTENT VARCHAR2(1000) NOT NULL,
    MESSAGE_ALL_DATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SEQ_REPLY;
CREATE TABLE TBL_REPLY(
	  ID NUMBER CONSTRAINT PK_REPLY PRIMARY KEY,
	  REPLY_CONTENT VARCHAR2(2000) NOT NULL,
	  CREATED_DATE DATE DEFAULT SYSDATE,
	  UPDATED_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE TBL_VOLUNTEER(
	  ID NUMBER CONSTRAINT PK_VOLUNTEER PRIMARY KEY,
	  VOLUNTEER_START_DATE DATE NOT NULL,
	  VOLUNTEER_END_DATE DATE NOT NULL,
	  VOLUNTEER_DEADLINE DATE NOT NULL,
	  CREATED_DATE DATE DEFAULT SYSDATE,
	  UPDATED_DATE DATE DEFAULT SYSDATE,
	  CONSTRAINT FK_VOLUNTEER_COURSE FOREIGN KEY(ID)
	  REFERENCES TBL_COURSE(ID)  ON DELETE CASCADE
);


CREATE SEQUENCE SEQ_REPORT;
CREATE TABLE TBL_REPORT(
      ID NUMBER CONSTRAINT PK_REPORT PRIMARY KEY,
      CREATED_DATE DATE DEFAULT SYSDATE,
      UPDATED_DATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SEQ_FEED;
CREATE TABLE TBL_FEED (
	  ID NUMBER CONSTRAINT PK_FEED PRIMARY KEY,
	  FEED_CONTENT VARCHAR2(2000) NOT NULL,
	  CREATED_DATE DATE DEFAULT SYSDATE,
	  UPDATED_DATE DATE DEFAULT SYSDATE
);


CREATE SEQUENCE SEQ_TAG;
CREATE TABLE TBL_TAG (
	  ID NUMBER CONSTRAINT PK_TAG PRIMARY KEY,
	  TAG_CONTENT VARCHAR2(2000) NOT NULL,
	  FEED_ID NUMBER NOT NULL,
	  CREATED_DATE DATE DEFAULT SYSDATE,
	  UPDATED_DATE DATE DEFAULT SYSDATE,
	  CONSTRAINT FK_TAG_FEED FOREIGN KEY(FEED_ID) REFERENCES TBL_FEED(ID) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_PATH;
CREATE TABLE TBL_PATH(
     ID NUMBER CONSTRAINT PK_ID PRIMARY KEY,
     PATH_NAME VARCHAR2(1000) NOT NULL,
     PATH_ADDRESS VARCHAR(1000) NOT NULL,
     COURSE_ID NUMBER NOT NULL,
     CREATED_DATE DATE DEFAULT SYSDATE,
     UPDATED_DATE DATE DEFAULT SYSDATE,
     CONSTRAINT FK_PATH_COURSE FOREIGN KEY(COURSE_ID)
     REFERENCES TBL_COURSE(ID)  ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_PLAN;
CREATE TABLE TBL_PLAN
(
    ID NUMBER CONSTRAINT PK_PLAN PRIMARY KEY,
    PLAN_NAME VARCHAR2(1000) NOT NULL,
    PLAN_START_DATE DATE DEFAULT SYSDATE,
    PLAN_END_DATE DATE DEFAULT SYSDATE,
    PLAN_DEADLINE DATE,
    PLAN_MAX_PERSONNEL NUMBER NOT NULL,
    PLAN_MIN_PERSONNEL NUMBER NOT NULL,
    PLAN_PRICE NUMBER NOT NULL,
    PLAN_START_ADDRESS VARCHAR2(2000) NOT NULL,
    PLAN_CONTENT VARCHAR2(2000) NOT NULL,
    PLAN_FILE_PATH VARCHAR2(2000),
    PLAN_FILE_SIZE VARCHAR2(2000),
    PLAN_FILE_NAME VARCHAR2(2000),
    MEMBER_ID NUMBER NOT NULL
        CONSTRAINT FK_PLAN_MEMBER
            REFERENCES TBL_MEMBER
                ON DELETE CASCADE,
    COURSE_ID NUMBER NOT NULL
        CONSTRAINT FK_PLAN_COURSE
            REFERENCES TBL_COURSE
                ON DELETE CASCADE,
    CREATED_DATE DATE DEFAULT SYSDATE,
    UPDATED_DATE DATE DEFAULT SYSDATE
);


CREATE TABLE TBL_FEED_REPORT(
      ID NUMBER CONSTRAINT PK_FEED_REPORT PRIMARY KEY,
      REPORTED_REASON VARCHAR2(200),
      REPORTED_ID  NUMBER NOT NULL,
      MEMBER_ID NUMBER NOT NULL,
      CREATED_DATE DATE DEFAULT SYSDATE,
      UPDATED_DATE DATE DEFAULT SYSDATE,
      CONSTRAINT FK_FEED_REPORT_REPORT FOREIGN KEY(ID) REFERENCES TBL_REPORT(ID)  ON DELETE CASCADE,
      CONSTRAINT FK_FEED_REPORT_FEED FOREIGN KEY(REPORTED_ID) REFERENCES TBL_FEED(ID)  ON DELETE CASCADE,
      CONSTRAINT FK_FEED_REPORT_MEMBER FOREIGN KEY(MEMBER_ID) REFERENCES TBL_MEMBER(ID)  ON DELETE CASCADE
);
CREATE SEQUENCE SEQ_FEED_TAG;
CREATE TABLE TBL_FEED_TAG(
     ID NUMBER CONSTRAINT PK_FEED_TAG PRIMARY KEY,
     FEED_TAG_CONTENT VARCHAR2(2000) NOT NULL,
     FEED_ID NUMBER NOT NULL,
     CONSTRAINT FK_FEED_TAG_FEED FOREIGN KEY(FEED_ID)
     REFERENCES TBL_FEED(ID) ON DELETE CASCADE
);

CREATE TABLE TBL_GENERAL_FEED (
	  ID NUMBER CONSTRAINT PK_GENERAL_FEED PRIMARY KEY,
	  MEMBER_ID NUMBER NOT NULL,
	  CONSTRAINT FK_GENERAL_FEED_FEED FOREIGN KEY(ID) REFERENCES TBL_FEED(ID)  ON DELETE CASCADE,
	  CONSTRAINT FK_GENERAL_FEED_MEMBER FOREIGN KEY(MEMBER_ID) REFERENCES TBL_MEMBER(ID)  ON DELETE CASCADE
);

CREATE TABLE TBL_RECEIVE_MESSAGE(
    ID NUMBER CONSTRAINT PK_RECEIVE_MESSAGE PRIMARY KEY,
    RECEIVER_ID NUMBER NOT NULL,
    SENDER_ID NUMBER NOT NULL,
    RECEIVE_MESSAGE_CHECK VARCHAR2(10) DEFAULT 'UNREAD',
    CONSTRAINT FK_RECEIVE_MESSAGE_MESSAGE FOREIGN KEY(ID)
    REFERENCES TBL_MESSAGE(ID) ON DELETE CASCADE,
    CONSTRAINT FK_RECEIVE_MESSAGE_RECEIVER FOREIGN KEY(RECEIVER_ID)
    REFERENCES TBL_MEMBER(ID) ON DELETE CASCADE,
    CONSTRAINT FK_RECEIVE_MESSAGE_SENDER FOREIGN KEY(SENDER_ID)
    REFERENCES TBL_MEMBER(ID) ON DELETE CASCADE
);

CREATE TABLE TBL_SEND_MESSAGE(
    ID NUMBER CONSTRAINT PK_SEND_MESSAGE PRIMARY KEY,
    RECEIVER_ID NUMBER NOT NULL,
    SENDER_ID NUMBER NOT NULL,
    CONSTRAINT FK_SEND_MESSAGE_MESSAGE FOREIGN KEY(ID)
    REFERENCES TBL_MESSAGE(ID) ON DELETE CASCADE,
    CONSTRAINT FK_SEND_MESSAGE_RECEIVER FOREIGN KEY(RECEIVER_ID)
    REFERENCES TBL_MEMBER(ID) ON DELETE CASCADE,
    CONSTRAINT FK_SEND_MESSAGE_SENDER FOREIGN KEY(SENDER_ID)
    REFERENCES TBL_MEMBER(ID) ON DELETE CASCADE
);

CREATE TABLE TBL_RECEIVE_MESSAGE_FILE (
    ID NUMBER CONSTRAINT PK_RECEIVE_MESSAGE_FILE PRIMARY KEY,
    RECEIVE_MESSAGE_FILE_ID NUMBER NOT NULL,
    CONSTRAINT FK_RECEIVE_MESSAGE_FILE FOREIGN KEY (ID)
    REFERENCES TBL_FILE(ID) ON DELETE CASCADE,
    CONSTRAINT FK_RECEIVE_MESSAGE_FILE_FILE FOREIGN KEY (RECEIVE_MESSAGE_FILE_ID)
    REFERENCES TBL_RECEIVE_MESSAGE(ID) ON DELETE CASCADE
);

CREATE TABLE TBL_SEND_MESSAGE_FILE (
	ID NUMBER CONSTRAINT PK_SEND_MESSAGE_FILE PRIMARY KEY,
	SEND_MESSAGE_FILE_ID NUMBER NOT NULL,
	CONSTRAINT FK_SEND_MESSAGE_FILE FOREIGN KEY (ID)
	REFERENCES TBL_FILE(ID) ON DELETE CASCADE,
	CONSTRAINT FK_SEND_MESSAGE_FILE_FILE FOREIGN KEY (SEND_MESSAGE_FILE_ID)
	REFERENCES TBL_SEND_MESSAGE(ID) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_PARTICIPANT;
CREATE TABLE TBL_PARTICIPANT (
	 ID NUMBER CONSTRAINT PK_PARTICIPANT PRIMARY KEY,
	 MEMBER_ID NUMBER NOT NULL,
	 PLAN_ID NUMBER NOT NULL,
	 CREATED_DATE DATE DEFAULT SYSDATE,
	 UPDATED_DATE DATE DEFAULT SYSDATE,
	 CONSTRAINT FK_PARTICIPANT_MEMBER FOREIGN KEY(MEMBER_ID)
	 REFERENCES TBL_MEMBER(ID) ON DELETE CASCADE ,
	 CONSTRAINT FK_PARTICIPANT_PLAN FOREIGN KEY(PLAN_ID)
	 REFERENCES TBL_PLAN(ID) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_PAY;
CREATE TABLE TBL_PAY(
        ID NUMBER CONSTRAINT PK_PAY PRIMARY KEY,
        PAY_PRICE NUMBER DEFAULT 0,
        PAY_METHOD VARCHAR2(1000) NOT NULL,
        PAY_CARD_COMPANY VARCHAR2(1000) DEFAULT NULL,
        MEMBER_ID NUMBER NOT NULL,
        PLAN_ID NUMBER NOT NULL,
        CREATE_DATE DATE DEFAULT SYSDATE,
        UPDATE_DATE DATE DEFAULT SYSDATE,
        CONSTRAINT FK_PAY_MEMBER FOREIGN KEY(MEMBER_ID)
        REFERENCES TBL_MEMBER(ID) ON DELETE CASCADE ,
        CONSTRAINT FK_PAY_PLAN FOREIGN KEY(PLAN_ID)
        REFERENCES TBL_PLAN(ID) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_QUESTION;
CREATE TABLE TBL_QUESTION (
	  ID NUMBER CONSTRAINT PK_QEUSTION PRIMARY KEY,
	  QUESTION_CONTENT VARCHAR2(1000) NOT NULL,
	  MEMBER_ID NUMBER NOT NULL,
	  PLAN_ID NUMBER NOT NULL,
	  CREATE_DATE DATE DEFAULT SYSDATE,
	  CONSTRAINT FK_QEUSTION_MEMBER FOREIGN KEY(MEMBER_ID)
	  REFERENCES TBL_MEMBER(ID) ON DELETE CASCADE,
	  CONSTRAINT FK_QEUSTION_PLAN FOREIGN KEY(PLAN_ID)
	  REFERENCES TBL_PLAN(ID) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_REAL_FEED;
CREATE TABLE TBL_REAL_FEED (
	   ID NUMBER CONSTRAINT PK_REAL_FEED PRIMARY KEY,
	   MEMBER_ID NUMBER NOT NULL,
	   PLAN_ID NUMBER NOT NULL,
	   CONSTRAINT FK_REAL_FEED_FEED FOREIGN KEY(ID) REFERENCES TBL_FEED(ID)  ON DELETE CASCADE,
	   CONSTRAINT FK_REAL_FEED_MEMBER FOREIGN KEY(MEMBER_ID) REFERENCES TBL_MEMBER(ID)  ON DELETE CASCADE,
	   CONSTRAINT FK_REAL_FEED_PLAN FOREIGN KEY(PLAN_ID) REFERENCES TBL_PLAN(ID)  ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_REAL_FILE;
CREATE TABLE TBL_REAL_FILE(
	  ID NUMBER CONSTRAINT PK_REAL_FILE PRIMARY KEY,
	  FEED_ID NUMBER NOT NULL,
	  CONSTRAINT FK_REAL_FILE_FILE FOREIGN KEY(ID)
	  REFERENCES TBL_FILE(ID) ON DELETE CASCADE ,
	  CONSTRAINT FK_REAL_FILE_REAL_FEED FOREIGN KEY(FEED_ID)
	  REFERENCES TBL_REAL_FEED(ID) ON DELETE CASCADE
);

CREATE TABLE TBL_REAL_REPLY(
   ID NUMBER CONSTRAINT PK_REAL_REPLY PRIMARY KEY,
   MEMBER_ID NUMBER NOT NULL,
   FEED_ID NUMBER NOT NULL,
   CONSTRAINT FK_REAL_REPLY_REPLY FOREIGN KEY(ID)
   REFERENCES TBL_REPLY(ID) ON DELETE CASCADE ,
   CONSTRAINT FK_REAL_REPLY_MEMBER FOREIGN KEY(MEMBER_ID)
   REFERENCES TBL_MEMBER(ID) ON DELETE CASCADE ,
   CONSTRAINT FK_REAL_REPLY_REAL_FEED FOREIGN KEY(FEED_ID)
   REFERENCES TBL_REAL_FEED(ID) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_REAL_STAR;
CREATE TABLE TBL_REAL_STAR(
	ID NUMBER CONSTRAINT PK_REAL_STAR PRIMARY KEY,
	REAL_STAR NUMBER(1) DEFAULT 0,
	FEED_ID NUMBER NOT NULL,
	CONSTRAINT FK_REAL_SART_REAL_FEED FOREIGN KEY(FEED_ID)
	REFERENCES TBL_REAL_FEED(ID) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_REAL_TAG;
CREATE TABLE TBL_REAL_TAG(
	 ID NUMBER CONSTRAINT PK_REAL_TAG PRIMARY KEY,
	 TAG_CONTENT VARCHAR2(2000) NOT NULL,
	 FEED_ID NUMBER NOT NULL,
	 CONSTRAINT FK_REAL_TAG_FEED FOREIGN KEY(FEED_ID)
	 REFERENCES TBL_FEED(ID) ON DELETE CASCADE
);

CREATE TABLE TBL_REPLY_REPORT(
	  ID NUMBER CONSTRAINT PK_REPLY_REPORT PRIMARY KEY,
	  REPORTED_REASON VARCHAR2(200),
	  REPORTED_ID  NUMBER NOT NULL,
	  MEMBER_ID NUMBER NOT NULL,
	  CREATED_DATE DATE DEFAULT SYSDATE,
	  UPDATED_DATE DATE DEFAULT SYSDATE,
	  CONSTRAINT FK_REPLY_REPORT_REPORT FOREIGN KEY(ID) REFERENCES TBL_REPORT(ID)  ON DELETE CASCADE,
	  CONSTRAINT FK_REPLY_REPORT_REPLY FOREIGN KEY(REPORTED_ID) REFERENCES TBL_REPLY(ID)  ON DELETE CASCADE,
	  CONSTRAINT FK_REPLY_REPORT_MEMBER FOREIGN KEY(MEMBER_ID) REFERENCES TBL_MEMBER(ID)  ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_SCHEDULE;
CREATE TABLE TBL_SCHEDULE(
	 ID NUMBER CONSTRAINT PK_SCHEDULE PRIMARY KEY,
	 SCHEDULE_CONTENT VARCHAR2(2000) NOT NULL,
	 STATUS  VARCHAR2(1000) DEFAULT 'ENABLE',
	 PLAN_ID NUMBER NOT NULL,
	 CONSTRAINT FK_SCHEDULE_PLAN FOREIGN KEY(PLAN_ID)
	 REFERENCES TBL_PLAN(ID) ON DELETE CASCADE
);

CREATE TABLE TBL_TOGETHER_FEED (
	   ID NUMBER CONSTRAINT PK_TOGETHER_FEED PRIMARY KEY,
	   MEMBER_ID NUMBER NOT NULL,
	   CONSTRAINT FK_TOGETHER_FEED_FEED FOREIGN KEY(ID) REFERENCES TBL_FEED(ID)  ON DELETE CASCADE,
	   CONSTRAINT FK_TOGETHER_FEED_MEMBER FOREIGN KEY(MEMBER_ID) REFERENCES TBL_MEMBER(ID)  ON DELETE CASCADE
);

CREATE TABLE TBL_TOGETHER_FILE(
	  ID NUMBER CONSTRAINT PK_TOGETHER_FILE PRIMARY KEY,
	  FEED_ID NUMBER NOT NULL,
	  CONSTRAINT FK_TOGETHER_FILE_FILE FOREIGN KEY(ID)
	  REFERENCES TBL_FILE(ID) ON DELETE CASCADE,
	  CONSTRAINT FK_TOGETHER_FILE_TOGETHER_FEED FOREIGN KEY(FEED_ID)
	  REFERENCES TBL_TOGETHER_FEED(ID) ON DELETE CASCADE
);

CREATE TABLE TBL_TOGETHER_REPLY(
	   ID NUMBER CONSTRAINT PK_TOGETHER_REPLY PRIMARY KEY,
	   MEMBER_ID NUMBER NOT NULL,
	   FEED_ID NUMBER NOT NULL,
	   CONSTRAINT FK_TOGETHER_REPLY_REPLY FOREIGN KEY(ID)
	   REFERENCES TBL_REPLY(ID) ON DELETE CASCADE,
	   CONSTRAINT FK_TOGETHER_REPLY_MEMBER FOREIGN KEY(MEMBER_ID)
	   REFERENCES TBL_MEMBER(ID) ON DELETE CASCADE,
	   CONSTRAINT FK_TOGETHE_REPLY_TOGETHE_FEED FOREIGN KEY(FEED_ID)
	   REFERENCES TBL_TOGETHER_FEED(ID) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_TOGETHER_TAG;
CREATE TABLE TBL_TOGETHER_TAG(
	 ID NUMBER CONSTRAINT PK_TOGETHER_TAG PRIMARY KEY,
	 TAG_CONTENT VARCHAR2(2000) NOT NULL,
	 FEED_ID NUMBER NOT NULL,
	 CONSTRAINT FK_TOGETHER_TAG_FEED FOREIGN KEY(FEED_ID)
	 REFERENCES TBL_FEED(ID) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_WISH;
CREATE TABLE TBL_WISH (
	  ID NUMBER CONSTRAINT PK_WISH PRIMARY KEY,
	  CREATED_DATE DATE DEFAULT SYSDATE,
	  UPDATED_DATE DATE DEFAULT SYSDATE,
	  MEMBER_ID NUMBER NOT NULL,
	  PLAN_ID NUMBER NOT NULL,
	  CONSTRAINT FK_WISH_MEMBER FOREIGN KEY(MEMBER_ID)
	  REFERENCES TBL_MEMBER(ID) ON DELETE CASCADE,
	  CONSTRAINT FK_WISH_PLAN FOREIGN KEY(PLAN_ID)
	  REFERENCES TBL_PLAN(ID) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_WRITE_EXCLUDE;
CREATE TABLE TBL_WRITE_EXCLUDE (
	 ID NUMBER CONSTRAINT PK_WRITE_EXCLUDE PRIMARY KEY,
	 EXCLUDE_CONTENT VARCHAR2(1000) DEFAULT '',
	 PLAN_ID NUMBER NOT NULL,
	 CONSTRAINT FK_EXCLUDE_PLAN FOREIGN KEY (PLAN_ID)
	 REFERENCES TBL_PLAN(ID) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_WRITE_INCLUDE;
CREATE TABLE TBL_WRITE_INCLUDE (
   ID NUMBER CONSTRAINT PK_WRITE_INCLUDE PRIMARY KEY,
   INCLUDE_CONTENT VARCHAR2(1000) DEFAULT '',
   PLAN_ID NUMBER NOT NULL,
   CONSTRAINT FK_INCLUDE_PLAN FOREIGN KEY (PLAN_ID)
   REFERENCES TBL_PLAN(ID) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_WRITE_PREPARE;
CREATE TABLE TBL_WRITE_PREPARE (
   ID NUMBER CONSTRAINT PK_WRITE_PREPARE PRIMARY KEY,
   PREPARE_CONTENT VARCHAR2(1000) DEFAULT '',
   PLAN_ID NUMBER NOT NULL,
   CONSTRAINT FK_PREPARE_PLAN FOREIGN KEY (PLAN_ID)
   REFERENCES TBL_PLAN(ID) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_NOTICE;
CREATE TABLE TBL_NOTICE(
   ID NUMBER CONSTRAINT PK_NOTICE PRIMARY KEY,
   NOTICE_TITLE VARCHAR2(1000) NOT NULL,
   NOTICE_CONTENT VARCHAR2(2000) NOT NULL,
   ADMIN_ID NUMBER NOT NULL,
   CREATED_DATE DATE DEFAULT SYSDATE,
   UPDATED_DATE DATE DEFAULT SYSDATE,
   CONSTRAINT FK_NOTICE_ADMIN FOREIGN KEY(ADMIN_ID)
   REFERENCES TBL_ADMIN(ID) ON DELETE CASCADE
);

CREATE TABLE TBL_GENERAL_REPLY(
	  ID NUMBER CONSTRAINT PK_GENERAL_REPLY PRIMARY KEY,
	  MEMBER_ID NUMBER NOT NULL,
	  FEED_ID NUMBER NOT NULL,
	  CONSTRAINT FK_GENERAL_REPLY_REPLY FOREIGN KEY(ID)
	  REFERENCES TBL_REPLY(ID) ON DELETE CASCADE ,
	  CONSTRAINT FK_GENERAL_REPLY_MEMBER FOREIGN KEY(MEMBER_ID)
	  REFERENCES TBL_MEMBER(ID) ON DELETE CASCADE,
	  CONSTRAINT FK_GENERAL_REPLY_GENERAL_FEED FOREIGN KEY(FEED_ID)
	  REFERENCES TBL_GENERAL_FEED(ID) ON DELETE CASCADE
);

CREATE TABLE TBL_GENERAL_FILE (
      ID NUMBER CONSTRAINT PK_GENERAL_FILE PRIMARY KEY,
      FEED_ID NUMBER NOT NULL,
      CONSTRAINT FK_GENERAL_FILE_FILE FOREIGN KEY(ID) REFERENCES TBL_FILE(ID) ON DELETE CASCADE ,
      CONSTRAINT FK_GENERAL_FILE_GENERAL_FEED FOREIGN KEY(FEED_ID) REFERENCES TBL_GENERAL_FEED(ID) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_ANSWER;
CREATE TABLE TBL_ANSWER (
    ID NUMBER CONSTRAINT PK_ANSWER PRIMARY KEY,
    ANSWER_CONTENT VARCHAR2(2000) NOT NULL,
    MEMBER_ID NUMBER NOT NULL,
    QUESTION_ID NUMBER NOT NULL,
    PLAN_ID NUMBER NOT NULL,
    CONSTRAINT FK_ANSWER_MEMBER FOREIGN KEY(MEMBER_ID)
    REFERENCES TBL_MEMBER(ID) ON DELETE CASCADE ,
    CONSTRAINT FK_ANSWER_QEUSTION FOREIGN KEY(QUESTION_ID)
    REFERENCES TBL_QUESTION(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ANSWER_PLAN FOREIGN KEY (PLAN_ID)
    REFERENCES TBL_PLAN(ID) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_VOLUNTEER_EXCLUDE;
CREATE TABLE TBL_VOLUNTEER_EXCLUDE(
     ID NUMBER CONSTRAINT PK_VOLUNTEER_EXCLUDE PRIMARY KEY,
     EXCLUDE_CONTENT VARCHAR2(1000),
     VOLUNTEER_ID NUMBER NOT NULL,
     CREATED_DATE DATE DEFAULT SYSDATE,
     UPDATED_DATE DATE DEFAULT SYSDATE,
     CONSTRAINT FK_EXCLUDE_VOLUNTEER FOREIGN KEY(VOLUNTEER_ID)
     REFERENCES TBL_VOLUNTEER(ID) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_VOLUNTEER_INCLUDE;
CREATE TABLE TBL_VOLUNTEER_INCLUDE(
     ID NUMBER CONSTRAINT PK_VOLUNTEER_INCLUDE PRIMARY KEY,
     INCLUDE_CONTENT VARCHAR2(1000),
     VOLUNTEER_ID NUMBER NOT NULL,
     CREATED_DATE DATE DEFAULT SYSDATE,
     UPDATED_DATE DATE DEFAULT SYSDATE,
     CONSTRAINT FK_INCLUDE_VOLUNTEER FOREIGN KEY(VOLUNTEER_ID)
     REFERENCES TBL_VOLUNTEER(ID) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_VOLUNTEER_PARTICIPANT;
CREATE TABLE TBL_VOLUNTEER_PARTICIPANT (
	 ID NUMBER CONSTRAINT PK_V_PARTICIPANT PRIMARY KEY,
	 MEMBER_ID NUMBER NOT NULL,
	 COURSE_ID NUMBER NOT NULL,
	 CREATED_DATE DATE DEFAULT SYSDATE,
	 UPDATED_DATE DATE DEFAULT SYSDATE,
	 CONSTRAINT FK_V_PARTICIPANT_MEMBER FOREIGN KEY(MEMBER_ID)
	 REFERENCES TBL_MEMBER(ID) ON DELETE CASCADE ,
	 CONSTRAINT FK_V_PARTICIPANT_COURSE FOREIGN KEY(COURSE_ID)
	 REFERENCES TBL_COURSE(ID) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_VOLUNTEER_PREPARE;
CREATE TABLE TBL_VOLUNTEER_PREPARE(
     ID NUMBER CONSTRAINT PK_VOLUNTEER_PREPARE PRIMARY KEY,
     PREPARE_CONTENT VARCHAR2(1000),
     VOLUNTEER_ID NUMBER NOT NULL,
     CREATED_DATE DATE DEFAULT SYSDATE,
     UPDATED_DATE DATE DEFAULT SYSDATE,
     CONSTRAINT FK_PREPARE_VOLUNTEER FOREIGN KEY(VOLUNTEER_ID)
     REFERENCES TBL_VOLUNTEER(ID) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_VOLUNTEER_SCHEDULE;
CREATE TABLE TBL_VOLUNTEER_SCHEDULE(
   ID NUMBER CONSTRAINT PK_VOLUNTEER_SCHEDULE PRIMARY KEY,
   SCHEDULE_CONTENT VARCHAR2(2000) NOT NULL,
   VOLUNTEER_ID NUMBER NOT NULL,
   CONSTRAINT FK_VOLUNTEER_SCHEDULE FOREIGN KEY(VOLUNTEER_ID)
   REFERENCES TBL_VOLUNTEER(ID) ON DELETE CASCADE
);





