/* 피드 전체 조회 */
CREATE VIEW VIEW_FEED AS
SELECT 'GENERAL' AS FEED_TYPE, F.ID, F.FEED_CONTENT, GF.MEMBER_ID, NULL AS REAL_FEED_STAR, NULL AS PLAN_ID, F.CREATE_DATE, F.UPDATE_DATE 
FROM TBL_FEED F
JOIN TBL_GENERAL_FEED GF ON F.ID = GF.ID
UNION ALL
SELECT 'TOGETHER' AS FEED_TYPE, F.ID, F.FEED_CONTENT, TF.MEMBER_ID, NULL AS REAL_FEED_STAR, NULL AS PLAN_ID, F.CREATE_DATE, F.UPDATE_DATE
FROM TBL_FEED F
JOIN TBL_TOGETHER_FEED TF ON F.ID = TF.ID
UNION ALL
SELECT 'REAL' AS FEED_TYPE, F.ID, F.FEED_CONTENT, RF.MEMBER_ID, RF.REAL_FEED_STAR, RF.PLAN_ID, F.CREATE_DATE, F.UPDATE_DATE
FROM TBL_FEED F
JOIN TBL_REAL_FEED RF ON F.ID = RF.ID;

/* 댓글 전체 조회 */

CREATE VIEW VIEW_REPLY AS
(
SELECT 'GENERAL' AS REPLY_TYPE, R.ID, R.REPLY_CONTENT , GR.MEMBER_ID, GR.GENERAL_FEED_ID FEED_ID, R.CREATE_DATE , R.UPDATE_DATE 
FROM TBL_REPLY R
JOIN TBL_GENERAL_REPLY GR ON R.ID = GR.ID
UNION ALL
SELECT 'TOGETHER' AS REPLY_TYPE, R.ID, R.REPLY_CONTENT , TR.MEMBER_ID, TR.TOGETHER_FEED_ID FEED_ID, R.CREATE_DATE , R.UPDATE_DATE 
FROM TBL_REPLY R
JOIN TBL_TOGETHER_REPLY TR ON R.ID = TR.ID
UNION ALL
SELECT 'REAL' AS REPLY_TYPE, R.ID, R.REPLY_CONTENT , RR.MEMBER_ID, RR.REAL_FEED_ID FEED_ID, R.CREATE_DATE , R.UPDATE_DATE 
FROM TBL_REPLY R
JOIN TBL_REAL_REPLY RR ON R.ID = RR.ID
);

/*받은메세지함의 보낸사람*/
CREATE VIEW VIEW_RECEIVE_MESSAGE_SENDER AS
(
SELECT 
M.ID MEMBER_ID, M.MEMBER_EMAIL, M.MEMBER_PASSWORD , M.MEMBER_NICKNAME , M.MEMBER_TELL , M.MEMBER_BIRTH , M.MEMBER_GENDER , M.MEMBER_POINT, 
R.ID SENDER_ID, R.RECEIVE_MESSAGE_SENDER ,
MESSAGE.MESSAGE_ALL_CONTENT , MESSAGE.MESSAGE_ALL_DATE
FROM TBL_MEMBER M
JOIN TBL_RECEIVE_MESSAGE R
ON M.ID = R.RECEIVE_MESSAGE_SENDER
JOIN TBL_MESSAGE MESSAGE
ON R.ID = MESSAGE.ID
);

/*보낸메세지함의 받은사람*/

CREATE VIEW VIEW_SEND_MESSAGE_RECEIVER AS
(
	SELECT
	M.ID MEMBER_ID, M.MEMBER_EMAIL ,M.MEMBER_PASSWORD ,M.MEMBER_NICKNAME ,M.MEMBER_TELL ,M.MEMBER_BIRTH ,M.MEMBER_GENDER ,M.MEMBER_POINT ,
	S.SEND_MESSAGE_RECEIVER,
	MESSAGE.MESSAGE_ALL_CONTENT ,MESSAGE.MESSAGE_ALL_DATE
	FROM TBL_MEMBER M
	JOIN TBL_SEND_MESSAGE S 
	ON M.ID = S.SEND_MESSAGE_RECEIVER 
	JOIN TBL_MESSAGE MESSAGE
	ON S.ID = MESSAGE.ID 
);