/*내가 찜한 코스*/
DROP VIEW VIEW_WISH_COURSEWISH_PLANWISH;
CREATE VIEW VIEW_WISH_COURSE_WISH AS
(
SELECT W.ID WISH, W.CREATE_DATE, W.UPDATE_DATE, C.ID COURSE_WISH, C.MEMBER_ID COURSE_MEMBER_ID, C.COURSE_ID
FROM TBL_WISH W 
JOIN TBL_COURSE_WISH C
ON W.ID = C.ID
);

SELECT * FROM VIEW_WISH_COURSE_WISH;

/*내가 찜한 계획*/
CREATE VIEW VIEW_WISH_PLAN_WISH AS
(
SELECT W.ID WISH_ID, W.CREATE_DATE , W.UPDATE_DATE , P.MEMBER_ID , P.PLAN_ID 
FROM TBL_WISH W
JOIN TBL_PLAN_WISH P
ON W.ID = P.ID
);

SELECT * FROM VIEW_WISH_PLAN_WISH;

/*받은메세지함의 받은사람*/

CREATE VIEW VIEW_RECEIVE_MESSAGE_RECEIVER AS
SELECT 
M.ID, M.MEMBER_NICKNAME , M.MEMBER_GENDER , 
R.ID RECEVE_ID, R.RECEIVE_MESSAGE_RECEIVER , R.RECEIVE_MESSAGE_CHECK, 
MESSAGE.MESSAGE_ALL_CONTENT ,MESSAGE.MESSAGE_ALL_DATE
FROM TBL_MEMBER M
JOIN TBL_RECEIVE_MESSAGE R
ON M.ID = R.RECEIVE_MESSAGE_RECEIVER 
JOIN TBL_MESSAGE MESSAGE
ON R.ID = MESSAGE.ID;

SELECT * FROM VIEW_RECEIVE_MESSAGE_RECEIVER ;

/*받은메세지함의 보낸사람*/

CREATE VIEW VIEW_RECEIVE_MESSAGE_SENDER AS
(
SELECT 
M.ID MEMBER_ID, M.MEMBER_EMAIL, M.MEMBER_PASSWORD , M.MEMBER_NICKNAME , M.MEMBER_TELL , M.MEMBER_BIRTH , M.MEMBER_GENDER , M.MEMBER_POINT, 
R.ID SENDER_ID, R.RECEIVE_MESSAGE_SENDER ,
MESSAGE.MESSAGE_ALL_CONTENT , MESSAGE.MESSAGE_ALL_DATE
FROM TBL_MEMBER M
JOIN TBL_RECEIVE_MESSAGE R
ON M.ID = R.RECEIVE_MESSAGE_SENDER
JOIN TBL_MESSAGE MESSAGE
ON R.ID = MESSAGE.ID
);

SELECT * FROM VIEW_RECEIVE_MESSAGE_SENDER;

/*보낸메세지함의 받은사람*/

CREATE VIEW VIEW_SEND_MESSAGE_RECEIVER AS
(
	SELECT
	M.ID MEMBER_ID, M.MEMBER_EMAIL ,M.MEMBER_PASSWORD ,M.MEMBER_NICKNAME ,M.MEMBER_TELL ,M.MEMBER_BIRTH ,M.MEMBER_GENDER ,M.MEMBER_POINT ,
	S.SEND_MESSAGE_RECEIVER,
	MESSAGE.MESSAGE_ALL_CONTENT ,MESSAGE.MESSAGE_ALL_DATE
	FROM TBL_MEMBER M
	JOIN TBL_SEND_MESSAGE S 
	ON M.ID = S.SEND_MESSAGE_RECEIVER 
	JOIN TBL_MESSAGE MESSAGE
	ON S.ID = MESSAGE.ID 
);

SELECT * FROM VIEW_SEND_MESSAGE_RECEIVER;

/*보낸메세지함의 보낸사람*/
CREATE VIEW VIEW_SEND_MESSAGE_SENDER AS 
(
	SELECT
	M.ID MEMBER_ID , M.MEMBER_EMAIL , M.MEMBER_PASSWORD , M.MEMBER_NICKNAME , M.MEMBER_TELL , M.MEMBER_BIRTH ,M.MEMBER_GENDER ,M.MEMBER_POINT ,
	S.SEND_MESSAGE_SENDER ,
	MESSAGE.MESSAGE_ALL_CONTENT , MESSAGE.MESSAGE_ALL_DATE
	FROM TBL_MEMBER M 
	JOIN TBL_SEND_MESSAGE S
	ON M.ID = S.SEND_MESSAGE_SENDER 
	JOIN TBL_MESSAGE MESSAGE
	ON S.ID = MESSAGE.ID
);


SELECT * FROM VIEW_SEND_MESSAGE_SENDER;
